/* Schema definition generated by prostgles-server */

export type DBGeneratedSchema = {
  users: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      id: string;
      username: string;
      type: string;
    };
  };
}


/**
 * Data types as expected when selecting from the database
 * */
export type DBSchema = {
  [K in keyof DBGeneratedSchema]: Required<DBGeneratedSchema[K]["columns"]>;
};

/**
 * Data types as expected when inserting into the database (optional fields might be nullable/with defaults)
 * */
export type DBSchemaForInsert = {
  [K in keyof DBGeneratedSchema]: DBGeneratedSchema[K]["columns"];
};

export type GeneratedFunctionSchema = Record<string, never>;