/* Schema definition generated by prostgles-server */

export type DBGeneratedSchema = {
  users: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      id: string;
      username: string;
      type: string;
    };
  };
}


export type GeneratedFunctionSchema = Record<string, never>;