/* This file was generated by Prostgles 
*/ 

 /* SCHEMA DEFINITON. Table names have been altered to work with Typescript */
/* DBO Definition */

export type DBSchemaGenerated = {
  access_control: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      connection_id: string;
      created?: null | Date;
      id?: number;
      name?: null | string;
      rule:       { 
        userGroupNames: string[];
        dbsPermissions?: {  createWorkspaces?: boolean; viewPublishedWorkspaces?: {  workspaceIds: string[]; }; };
        dbPermissions: 
        | {  type: 'Run SQL'; allowSQL?: boolean; }
        | {  type: 'All views/tables'; allowAllTables: string[]; }
        | {  type: 'Custom'; customTables: any[]; }; 
      };
    };
  };
  access_control_user_types: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      access_control_id: number;
      user_type: string;
    };
  };
  backups: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      connection_details?: string;
      connection_id?: null | string;
      content_type?: string;
      created?: Date;
      credential_id?: null | number;
      dbSizeInBytes: number;
      destination: string;
      details?: null | any;
      dump_command: string;
      dump_logs?: null | string;
      id?: string;
      initiator?: null | string;
      last_updated?: Date;
      options: 
        | {  command: 'pg_dumpall'; clean: boolean; dataOnly?: boolean; globalsOnly?: boolean; rolesOnly?: boolean; schemaOnly?: boolean; ifExists?: boolean; encoding?: string; keepLogs?: boolean; }
        | {  command: 'pg_dump'; format: 'p' | 't' | 'c'; dataOnly?: boolean; clean?: boolean; create?: boolean; encoding?: string; numberOfJobs?: number; noOwner?: boolean; compressionLevel?: number; ifExists?: boolean; keepLogs?: boolean; }
      restore_command?: null | string;
      restore_end?: null | Date;
      restore_logs?: null | string;
      restore_options?:       { 
        command: 'pg_restore' | 'psql';
        format: 'p' | 't' | 'c';
        clean: boolean;
        newDbName?: string;
        create?: boolean;
        dataOnly?: boolean;
        noOwner?: boolean;
        numberOfJobs?: number;
        ifExists?: boolean;
        keepLogs?: boolean; 
      };
      restore_start?: null | Date;
      restore_status?: 
        | null
        | {  ok: string; }
        | {  err: string; }
        | {  loading: {  loaded: number; total: number; }; }
      sizeInBytes?: null | number;
      status: 
        | {  ok: string; }
        | {  err: string; }
        | {  loading?: {  loaded: number; total: number; }; }
      uploaded?: null | Date;
    };
  };
  connections: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      backups_config?: null |       { 
        enabled?: boolean;
        cloudConfig: null | {  credential_id?: null | number; };
        frequency: 'daily' | 'monthly' | 'weekly' | 'hourly';
        hour?: number;
        dayOfWeek?: number;
        dayOfMonth?: number;
        keepLast?: number;
        err?: null | string;
        dump_options: 
        | {  command: 'pg_dumpall'; clean: boolean; dataOnly?: boolean; globalsOnly?: boolean; rolesOnly?: boolean; schemaOnly?: boolean; ifExists?: boolean; encoding?: string; keepLogs?: boolean; }
        | {  command: 'pg_dump'; format: 'p' | 't' | 'c'; dataOnly?: boolean; clean?: boolean; create?: boolean; encoding?: string; numberOfJobs?: number; noOwner?: boolean; compressionLevel?: number; ifExists?: boolean; keepLogs?: boolean; }; 
      };
      created?: null | Date;
      db_conn?: null | string;
      db_host?: null | string;
      db_name?: null | string;
      db_pass?: null | string;
      db_port?: null | number;
      db_ssl?: "disable" | "allow" | "prefer" | "require" | "verify-ca" | "verify-full"
      db_user?: null | string;
      db_watch_shema?: null | boolean;
      id?: string;
      is_state_db?: null | boolean;
      last_updated?: number;
      name?: null | string;
      prgl_params?: null | any;
      prgl_url?: null | string;
      ssl_certificate?: null | string;
      ssl_client_certificate?: null | string;
      ssl_client_certificate_key?: null | string;
      ssl_reject_unauthorized?: null | boolean;
      table_config?: null |       { 
        fileTable?: string;
        storageType: 
        | {  type: 'local'; }
        | {  type: 'S3'; credential_id: number; };
        referencedTables?: {  };
        delayedDelete?: {  deleteAfterNDays: number; checkIntervalHours?: number; }; 
      };
      type?: string;
      user_id?: null | string;
    };
  };
  credential_types: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      id: string;
    };
  };
  credentials: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      bucket?: null | string;
      id?: number;
      key_id: string;
      key_secret: string;
      name?: string;
      region?: null | string;
      type?: string;
      user_id?: null | string;
    };
  };
  global_settings: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      allowed_ips?: Array<string>;
      allowed_ips_enabled?: boolean;
      allowed_origin?: null | string;
      id?: number;
      trust_proxy?: boolean;
      updated_by?: "user" | "app"
    };
  };
  links: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      closed?: null | boolean;
      created?: null | Date;
      deleted?: null | boolean;
      id?: string;
      last_updated: number;
      options?: any;
      user_id: string;
      w1_id: string;
      w2_id: string;
      workspace_id: string;
    };
  };
  magic_links: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      expires: number;
      id?: string;
      magic_link?: null | string;
      magic_link_used?: null | Date;
      user_id: string;
    };
  };
  sessions: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      active?: null | boolean;
      created?: null | Date;
      expires: number;
      id?: string;
      ip_address: string;
      is_connected?: null | boolean;
      is_mobile?: null | boolean;
      last_used?: null | Date;
      name?: null | string;
      project_id?: null | string;
      type?: "web" | "api_token"
      user_id: string;
      user_type: string;
    };
  };
  user_groups: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      filter?: null | any;
      id: string;
    };
  };
  user_statuses: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      id: string;
    };
  };
  user_types: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      id: string;
    };
  };
  users: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      "2fa"?: null |       { 
        secret: string;
        recoveryCode: string;
        enabled: boolean; 
      };
      created?: null | Date;
      id?: string;
      last_updated?: null | number;
      no_password?: null | boolean;
      options?: null |       { 
        showStateDB?: boolean;
        hideNonSSLWarning?: boolean; 
      };
      password?: string;
      status?: string;
      type?: string;
      username: string;
    };
  };
  windows: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      closed?: null | boolean;
      columns?: any;
      created?: null | Date;
      deleted?: null | boolean;
      filter?: any;
      fullscreen?: null | boolean;
      id?: string;
      last_updated: number;
      layout?: null | any;
      limit?: null | number;
      name?: null | string;
      nested_tables?: null | any;
      options?: any;
      selected_sql?: string;
      show_menu?: null | boolean;
      sort?: null | any;
      sql?: string;
      sql_options?:       { 
        executeOptions?: 'full' | 'block';
        errorMessageDisplay?: 'tooltip' | 'bottom' | 'both';
        tabSize?: number;
        lineNumbers?: 'on' | 'off';
        minimap?: {  enabled: boolean; }; 
      };
      table_name?: null | string;
      table_oid?: null | number;
      type?: null | string;
      user_id: string;
      workspace_id: string;
    };
  };
  workspaces: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      active_row?: null | any;
      connection_id: string;
      created?: null | Date;
      deleted?: boolean;
      id?: string;
      last_updated: number;
      layout?: null | any;
      name?: string;
      options?:       { 
        hideCounts?: boolean;
        showAllMyQueries?: boolean;
        defaultLayoutType?: 'row' | 'tab' | 'col';
        pinnedMenu?: boolean; 
      };
      published?: boolean;
      url_path?: null | string;
      user_id: string;
    };
  };
  
}
