/* This file was generated by Prostgles 
*/ 

 /* SCHEMA DEFINITON. Table names have been altered to work with Typescript */
/* DBO Definition */

export type DBSchemaGenerated = {
  access_control: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      connection_id: string;
      created?: Date | null;
      id?: string;
      rule?: any | null
    };
  };
  access_control_user_types: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      access_control_id: string;
      user_type: string
    };
  };
  connections: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      access_control?: any | null;
      created?: Date | null;
      db_conn?: string | null;
      db_host?: string | null;
      db_name?: string | null;
      db_pass?: string | null;
      db_port?: number | null;
      db_ssl?: string;
      db_user?: string | null;
      db_watch_shema?: boolean | null;
      id?: string;
      is_state_db?: boolean | null;
      last_updated?: number;
      name?: string | null;
      prgl_params?: any | null;
      prgl_url?: string | null;
      table_config?: any | null;
      type?: string;
      user_id: string
    };
  };
  credentials: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      connection_id: string;
      id?: number;
      key_id: string;
      key_secret: string;
      type: string;
      user_id?: string | null
    };
  };
  geography_columns: {
    is_view: true;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      coord_dimension?: number | null;
      f_geography_column?: string | null;
      f_table_catalog?: string | null;
      f_table_name?: string | null;
      f_table_schema?: string | null;
      srid?: number | null;
      type?: string | null
    };
  };
  geometry_columns: {
    is_view: true;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      coord_dimension?: number | null;
      f_geometry_column?: string | null;
      f_table_catalog?: string | null;
      f_table_name?: string | null;
      f_table_schema?: string | null;
      srid?: number | null;
      type?: string | null
    };
  };
  globals: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      onerow_id?: boolean;
      user_groups?: any | null
    };
  };
  links: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      closed?: boolean | null;
      created?: Date | null;
      deleted?: boolean | null;
      id?: string;
      last_updated: number;
      options?: any;
      user_id: string;
      w1_id: string;
      w2_id: string;
      workspace_id: string
    };
  };
  magic_links: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      expires: number;
      id?: string;
      magic_link?: string | null;
      magic_link_used?: Date | null;
      user_id?: string | null
    };
  };
  sessions: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      active?: boolean | null;
      created?: Date | null;
      expires: number;
      id?: string;
      is_mobile?: boolean | null;
      project_id?: string | null;
      type?: string | null;
      user_id?: string | null;
      user_type: string
    };
  };
  spatial_ref_sys: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      auth_name?: string | null;
      auth_srid?: number | null;
      proj4text?: string | null;
      srid: number;
      srtext?: string | null
    };
  };
  user_groups: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      filter?: any | null;
      id: string
    };
  };
  user_statuses: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      id: string
    };
  };
  user_types: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      id: string
    };
  };
  users: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      created?: Date | null;
      id?: string;
      last_updated?: number | null;
      password?: string;
      status?: string;
      type?: string;
      username: string
    };
  };
  windows: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      closed?: boolean | null;
      columns?: any | null;
      created?: Date | null;
      deleted?: boolean | null;
      filter?: any | null;
      fullscreen?: boolean | null;
      id?: string;
      last_updated: number;
      layout?: any | null;
      limit?: number | null;
      name?: string | null;
      nested_tables?: any | null;
      options?: any | null;
      selected_sql?: string;
      show_menu?: boolean | null;
      sort?: any | null;
      sql?: string;
      table_name?: string | null;
      table_oid?: number | null;
      type?: string | null;
      user_id: string;
      workspace_id: string
    };
  };
  workspaces: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      active_row?: any | null;
      connection_id: string;
      created?: Date | null;
      deleted?: boolean;
      id?: string;
      last_updated: number;
      layout?: any | null;
      name?: string;
      options?: any | null;
      url_path?: string | null;
      user_id: string
    };
  };
  
}
